# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-arm64
aiohttp=3.9.3=py312he37b823_1
aiosignal=1.3.1=pyhd8ed1ab_0
aom=3.8.2=h078ce10_0
attrs=23.2.0=pyh71513ae_0
blas=1.0=openblas
blosc=1.21.5=h9c252e8_1
brotli=1.1.0=hb547adb_1
brotli-bin=1.1.0=hb547adb_1
brotli-python=1.1.0=py312h9f69965_1
bzip2=1.0.8=h80987f9_5
c-ares=1.28.1=h93a5062_0
c-blosc2=2.14.4=ha57e6be_1
ca-certificates=2024.3.11=hca03da5_0
cairo=1.18.0=hd1e100b_0
cctools_osx-arm64=986=h62378fb_0
certifi=2024.6.2=py312hca03da5_0
cffi=1.16.0=py312h8e38eb3_0
charset-normalizer=3.3.2=pyhd8ed1ab_0
clang=16.0.6=h30cc82d_6
clang-16=16.0.6=default_he012953_6
clang_impl_osx-arm64=16.0.6=hc421ffc_11
clang_osx-arm64=16.0.6=h54d7cd3_11
clangxx=16.0.6=default_h4cf2255_6
clangxx_impl_osx-arm64=16.0.6=hcd7bac0_11
clangxx_osx-arm64=16.0.6=h54d7cd3_11
compiler-rt=16.0.6=h3808999_2
compiler-rt_osx-arm64=16.0.6=h3808999_2
contourpy=1.2.1=py312h0fef576_0
cycler=0.12.1=pyhd8ed1ab_0
dav1d=1.2.1=hb547adb_0
double-conversion=3.3.0=h13dd4ca_0
eigen=3.4.0=h1995070_0
expat=2.5.0=h313beb8_0
fenics-basix=0.7.0=py312hb23e587_1
fenics-basix-pybind11-abi=0.4.16=hfeba48c_1
fenics-dolfinx=0.7.3=py312h23eab24_102
fenics-ffcx=0.7.0=pyh4af843d_0
fenics-libbasix=0.7.0=hb1687fd_1
fenics-libdolfinx=0.7.3=h44484f0_102
fenics-ufcx=0.7.0=h4af843d_0
fenics-ufl=2023.2.0=pyhd8ed1ab_0
ffmpeg=6.1.1=gpl_h4f1e072_108
fftw=3.3.10=mpi_mpich_h0cb5807_8
fltk=1.3.9=h31b9a01_0
font-ttf-dejavu-sans-mono=2.37=hab24e00_0
font-ttf-inconsolata=3.000=h77eed37_0
font-ttf-source-code-pro=2.038=h77eed37_0
font-ttf-ubuntu=0.83=h77eed37_1
fontconfig=2.14.2=h82840c6_0
fonts-conda-ecosystem=1=0
fonts-conda-forge=1=0
fonttools=4.51.0=py312he37b823_0
freeimage=3.18.0=hd0e3f39_20
freetype=2.12.1=hadb7bae_2
fribidi=1.0.10=h27ca646_0
frozenlist=1.4.1=py312he37b823_0
gettext=0.22.5=h8fbad5d_2
gettext-tools=0.22.5=h8fbad5d_2
gl2ps=1.4.2=h17b34a0_0
glew=2.1.0=h9f76cd9_2
glib=2.80.0=hfc324ee_4
glib-tools=2.80.0=hb9a4d99_4
gmp=6.3.0=hebf3989_1
gmsh=4.12.2=hd427cfb_0
gnutls=3.7.9=hd26332c_0
graphite2=1.3.13=hebf3989_1003
gst-plugins-base=1.24.1=h09b4b5e_1
gstreamer=1.24.1=h551c6ff_1
harfbuzz=8.3.0=h8f0ba13_0
hdf4=4.2.15=h2ee6834_7
hdf5=1.14.3=mpi_mpich_h754b83b_0
hypre=2.28.0=mpi_mpich_hd226f01_0
icu=73.2=hc8870d7_0
idna=3.6=pyhd8ed1ab_0
imath=3.1.11=h1059232_0
jsoncpp=1.9.5=hc021e02_1
jxrlib=1.1=h1a28f6b_2
kahip=3.16=py312h4d8faec_2
kahip-python=3.16=py312h381a4fd_2
kiwisolver=1.4.5=py312h389731b_1
krb5=1.21.2=h92f50d5_0
lame=3.100=h1a8c8d9_1003
lcms2=2.16=ha0e7c42_0
ld64_osx-arm64=711=ha4bd21c_0
lerc=4.0.0=h9a09cb3_0
libabseil=20240116.1=cxx17_hebf3989_2
libadios2=2.9.2=mpi_mpich_hc705787_2
libaec=1.1.3=hebf3989_0
libasprintf=0.22.5=h8fbad5d_2
libasprintf-devel=0.22.5=h8fbad5d_2
libass=0.17.1=hf7da4fe_1
libblas=3.9.0=22_osxarm64_openblas
libboost=1.84.0=h8e0f962_2
libboost-devel=1.84.0=hf450f58_2
libboost-headers=1.84.0=hce30654_2
libbrotlicommon=1.1.0=hb547adb_1
libbrotlidec=1.1.0=hb547adb_1
libbrotlienc=1.1.0=hb547adb_1
libcblas=3.9.0=22_osxarm64_openblas
libclang-cpp15=15.0.7=default_he012953_5
libclang-cpp16=16.0.6=default_he012953_6
libclang13=18.1.3=default_h83d0a53_0
libcurl=8.7.1=h2d989ff_0
libcxx=16.0.6=h4653b0c_0
libdeflate=1.20=h93a5062_0
libedit=3.1.20191231=hc8eb9b7_2
libev=4.33=h93a5062_2
libexpat=2.5.0=hb7217d7_1
libffi=3.4.4=hca03da5_0
libgettextpo=0.22.5=h8fbad5d_2
libgettextpo-devel=0.22.5=h8fbad5d_2
libgfortran=5.0.0=13_2_0_hd922786_3
libgfortran5=13.2.0=hf226fd6_3
libglib=2.80.0=hfc324ee_4
libhwloc=2.10.0=default_h52d8fe8_1000
libiconv=1.17=h0d3ecfb_2
libidn2=2.3.7=h93a5062_0
libintl=0.22.5=h8fbad5d_2
libintl-devel=0.22.5=h8fbad5d_2
libjpeg-turbo=3.0.0=hb547adb_1
liblapack=3.9.0=22_osxarm64_openblas
libllvm15=15.0.7=h2621b3d_4
libllvm16=16.0.6=haab561b_3
libllvm18=18.1.3=h30cc82d_0
libnetcdf=4.9.2=nompi_h291a7c2_113
libnghttp2=1.58.0=ha4dd798_1
libogg=1.3.4=h27ca646_1
libopenblas=0.3.27=openmp_h6c19121_0
libopenvino=2024.0.0=h200475e_5
libopenvino-arm-cpu-plugin=2024.0.0=h200475e_5
libopenvino-auto-batch-plugin=2024.0.0=hfaea8b3_5
libopenvino-auto-plugin=2024.0.0=hfaea8b3_5
libopenvino-hetero-plugin=2024.0.0=hc7e6747_5
libopenvino-ir-frontend=2024.0.0=hc7e6747_5
libopenvino-onnx-frontend=2024.0.0=h25b35cd_5
libopenvino-paddle-frontend=2024.0.0=h25b35cd_5
libopenvino-pytorch-frontend=2024.0.0=h3f3aa29_5
libopenvino-tensorflow-frontend=2024.0.0=hbc2fe69_5
libopenvino-tensorflow-lite-frontend=2024.0.0=h3f3aa29_5
libopus=1.3.1=h27ca646_1
libpng=1.6.43=h091b4b1_0
libpq=16.2=h0f8b458_1
libprotobuf=4.25.3=hbfab5d5_0
libptscotch=7.0.4=h5340af2_1
libraw=0.21.1=h2ee6834_2
libscotch=7.0.4=hc938e73_1
libsodium=1.0.18=h27ca646_1
libsqlite=3.45.2=h091b4b1_0
libssh2=1.11.0=h7a5bd25_0
libtasn1=4.19.0=h1a8c8d9_0
libtheora=1.1.1=h3422bc3_1005
libtiff=4.6.0=h07db509_3
libunistring=0.9.10=h3422bc3_0
libvorbis=1.3.7=h9f76cd9_0
libvpx=1.14.0=h078ce10_0
libwebp-base=1.3.2=h93a5062_1
libxcb=1.15=hf346824_0
libxml2=2.12.6=h0d0cfa8_1
libzip=1.10.1=ha0bc3c6_3
libzlib=1.2.13=h53f4e23_5
llvm-openmp=18.1.3=hcd81f8e_0
llvm-tools=16.0.6=haab561b_3
loguru=0.7.2=py312h81bd7bf_1
lz4-c=1.9.4=hb7217d7_0
matplotlib-base=3.8.4=py312ha6faf65_0
metis=5.1.0=h13dd4ca_1007
mpfr=4.2.1=h41d338b_1
mpi=1.0=mpich
mpi4py=3.1.5=py312h8d05a6a_1
mpich=4.2.0=hd4b5bf3_100
msgpack-python=1.0.7=py312h76e736e_0
multidict=6.0.5=py312h670c8ac_0
mumps-include=5.6.2=hce30654_4
mumps-mpi=5.6.2=ha94434e_4
munkres=1.1.4=pyh9f0ad1d_0
mysql-common=8.3.0=hd1853d3_4
mysql-libs=8.3.0=hf036fc4_4
ncurses=6.4=h313beb8_0
nettle=3.9.1=h40ed0f5_0
nlohmann_json=3.11.3=hebf3989_0
nspr=4.35=hb7217d7_0
nss=3.98=h5ce2875_0
numpy=1.26.4=py312h8442bc7_0
occt=7.7.2=all_h1e2436f_201
openexr=3.2.2=h2c51e1d_1
openh264=2.4.1=hebf3989_0
openjpeg=2.5.2=h9f1df11_0
openssl=3.2.1=h0d3ecfb_1
p11-kit=0.24.1=h29577a5_0
packaging=24.0=pyhd8ed1ab_0
parmetis=4.0.3=hefa2a9d_1005
pcre2=10.43=h26f9a81_0
petsc=3.20.6=real_h7646cce_100
petsc4py=3.20.5=real_hd567e68_100
pillow=10.3.0=py312h8a801b1_0
pip=23.3.1=py312hca03da5_0
pixman=0.43.4=hebf3989_0
pkg-config=0.29.2=hab62308_1008
platformdirs=4.2.0=pyhd8ed1ab_0
pooch=1.8.1=pyhd8ed1ab_0
proj=9.3.1=h93d94ba_0
pthread-stubs=0.4=h27ca646_1001
ptscotch=7.0.4=heaa5b5c_1
pugixml=1.14=h13dd4ca_0
pybind11-abi=4=hd8ed1ab_3
pycparser=2.22=pyhd8ed1ab_0
pyparsing=3.1.2=pyhd8ed1ab_0
pysocks=1.7.1=pyha2e5f31_6
python=3.12.2=hdf0ec26_0_cpython
python-dateutil=2.9.0=pyhd8ed1ab_0
python-gmsh=4.12.2=h57928b3_0
python_abi=3.12=4_cp312
pyvista=0.43.5=pyhd8ed1ab_0
qt-main=5.15.8=hf679f28_21
rapidjson=1.1.0=h48ca7d4_1
readline=8.2=h1a28f6b_0
requests=2.31.0=pyhd8ed1ab_0
scalapack=2.2.0=hb170938_1
scipy=1.12.0=py312hfa28a95_0
scooby=0.9.2=pyhd8ed1ab_0
scotch=7.0.4=heaa5b5c_1
setuptools=68.2.2=py312hca03da5_0
sigtool=0.1.3=h44b9a77_0
six=1.16.0=pyh6c4a22f_0
slepc=3.20.2=real_h35c204a_100
slepc4py=3.20.2=real_hec853a8_100
snappy=1.2.0=hd04f947_1
sqlite=3.41.2=h80987f9_0
suitesparse=5.10.1=h79486c6_3
superlu=5.2.2=hc615359_0
superlu_dist=8.2.1=hd666faf_1
svt-av1=2.0.0=h078ce10_0
tapi=1100.0.11=he4954df_0
tbb=2021.12.0=h2ffa867_0
tbb-devel=2021.12.0=hf0e5eac_0
tk=8.6.13=h5083fa2_1
tzdata=2024a=h04d1e81_0
urllib3=2.2.1=pyhd8ed1ab_0
utfcpp=4.0.5=hce30654_0
vtk=9.2.6=qt_py312h1234567_220
vtk-base=9.2.6=qt_py312h1234567_220
vtk-io-ffmpeg=9.2.6=qt_py312h1234567_220
wheel=0.41.2=py312hca03da5_0
wslink=2.0.0=pyhd8ed1ab_0
x264=1!164.3095=h57fd34a_2
x265=3.5=hbc6ce65_3
xorg-fixesproto=5.0=h3422bc3_1002
xorg-kbproto=1.0.7=h27ca646_1002
xorg-libice=1.1.1=hb547adb_0
xorg-libsm=1.2.4=hb547adb_0
xorg-libx11=1.8.9=h570a39f_0
xorg-libxau=1.0.11=hb547adb_0
xorg-libxdmcp=1.1.3=h27ca646_0
xorg-libxext=1.3.4=h1a8c8d9_2
xorg-libxfixes=5.0.3=h3422bc3_1004
xorg-libxrender=0.9.11=hb547adb_0
xorg-renderproto=0.11.1=h27ca646_1002
xorg-xextproto=7.3.0=h1a8c8d9_1003
xorg-xproto=7.0.31=h1a28f6b_1007
xz=5.4.6=h80987f9_0
yaml=0.2.5=h3422bc3_2
yarl=1.9.4=py312he37b823_0
zeromq=4.3.5=hebf3989_1
zfp=0.5.5=hcfdfaf5_8
zlib=1.2.13=h53f4e23_5
zlib-ng=2.0.7=h1a8c8d9_0
zstd=1.5.5=h4f39d0f_0
